POST http://localhost:3001/api/users
Content-Type: application/json

# {
#   "username":"hellas",
#   "name":"Arto Hellas",
#   "password":"8day1fdds"
# }

{
  "username":"mluukkai",
  "name":"Matti Luukkainen",
  "password":"Ldd03sd2J"
}
